//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code wird erneut generiert. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace hsDotNet.Account {
    
    
    public partial class Manage {
        
        /// <summary>
        /// successMessage-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder successMessage;
        
        /// <summary>
        /// setPassword-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder setPassword;
        
        /// <summary>
        /// password-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox password;
        
        /// <summary>
        /// confirmPassword-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox confirmPassword;
        
        /// <summary>
        /// changePassword-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder changePasswordHolder;
        
        /// <summary>
        /// changePasswordUserName-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label changePasswordUserName;
        
        /// <summary>
        /// CurrentPasswordLabel-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label CurrentPasswordLabel;
        
        /// <summary>
        /// CurrentPassword-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox CurrentPassword;
        
        /// <summary>
        /// NewPasswordLabel-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label NewPasswordLabel;
        
        /// <summary>
        /// NewPassword-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox NewPassword;
        
        /// <summary>
        /// ConfirmNewPasswordLabel-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ConfirmNewPasswordLabel;
        
        /// <summary>
        /// ConfirmNewPassword-Steuerelement
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Zum Ändern die Felddeklaration aus der Designerdatei in die CodeBehind-Datei verschieben.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ConfirmNewPassword;
    }
}
